version: "3.8"
services:
  php-apache:
    container_name: php-apache
    build:
      context: ./
    ports:
      - "800:80"
      - "443:443"
    volumes:
      - ./application:/var/www/html
      - ./.docker/vhost.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./.docker/entrypoint:/var/www/html/entrypoint
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - network

  database:
    image: postgres:12
    container_name: db-postgres
    restart: unless-stopped
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/database/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    networks:
      - network
  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "root@root.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    ports:
      - "1616:80"
    networks:
      - network

networks:
  network:
    name: network
    driver: bridge
