version: "3.8"
services:
  php-apache:
    container_name: php-apache
    build:
      context: ./
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site/wwwroot:/var/www/html
      - ${WEBAPP_STORAGE_HOME}/site/wwwroot/.docker/vhost.conf:/etc/apache2/sites-enabled/000-default.conf
      - ${WEBAPP_STORAGE_HOME}/site/wwwroot/.docker/entrypoint:/var/www/html/entrypoint
      - ${WEBAPP_STORAGE_HOME}/site/wwwroot/./docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - network

  database:
    image: postgres:12
    container_name: db-postgres
    restart: unless-stopped
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    networks:
      - network

networks:
  network:
    name: network
    driver: bridge
    
volumes:
  dbdata:
