version: "3.8"
services:
  php-apache:
    container_name: laravel-app
    build: .
    ports:
      - "8000:80"
      # - "8443:443"
    volumes:
      - ./application:/usr/share/nginx

    networks:
      - network

  database:
    image: postgres:12
    container_name: db-postgres
    restart: unless-stopped
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    networks:
      - network
networks:
  network:
    name: network
    driver: bridge
    
volumes:
  dbdata:
